version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
      - my-network
    
  

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
